### ISSUE TITLE
what's version of OpenBabel in PRosettaC?

### ISSUE THREAD

**Issue by autodataming** [LondonLab/PRosettaC#2]
what's version of OpenBabel in PRosettaC?

**Comment by danielzaidman** [comment]
Hi, sorry for the delayed reply, I've just seen it today.
I seem to not have access to the server anymore (I finished my PhD and started my postdoc), but I think you can just use the newest one. It was only used for very basic stuff, like switching between pdb, sdf and smiles.
Hope that helps.
Feel free to contact me by email if you have more questions:
daniel.zaidman@gmail.com

Best, Daniel.
